create table item (id int8 generated by default as identity, date timestamp, total_cost float8, primary key (id));
create table item_list_of_purchase (item_id int8 not null, list_of_purchase_id int8 not null);
create table product (id int8 generated by default as identity, name varchar(255), price float8, primary key (id));
alter table if exists item_list_of_purchase add constraint UK_r2f43a0re6pe3csjtjt374xon unique (list_of_purchase_id);
alter table if exists item_list_of_purchase add constraint FKfiypeqcryogevrh0ug9flg4ps foreign key (list_of_purchase_id) references product;
alter table if exists item_list_of_purchase add constraint FKf9wwcdnbf2ido14w5doxj1glo foreign key (item_id) references item;